# Generated by Django 3.0.8 on 2020-08-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('prod_name', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('for_whom', models.CharField(blank=True, max_length=10, null=True)),
                ('im1', models.ImageField(blank=True, default='', null=True, upload_to='images/products')),
                ('im2', models.ImageField(blank=True, default='', null=True, upload_to='images/products')),
                ('im3', models.ImageField(blank=True, default='', null=True, upload_to='images/products')),
                ('im4', models.ImageField(blank=True, default='', null=True, upload_to='images/products')),
                ('im5', models.ImageField(blank=True, default='', null=True, upload_to='images/products')),
            ],
        ),
    ]
