# Generated by Django 3.0.8 on 2020-08-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_auto_20200805_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
