# Generated by Django 3.0.8 on 2020-08-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyersAuthentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=300)),
                ('phone', models.CharField(max_length=14)),
            ],
        ),
    ]
