# Generated by Django 3.0.8 on 2020-08-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='password',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
