# Generated by Django 3.0.8 on 2020-08-03 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyersauthentication',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buyersauthentication',
            name='address',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='buyersauthentication',
            name='email',
            field=models.EmailField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='buyersauthentication',
            name='full_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='buyersauthentication',
            name='phone',
            field=models.CharField(default='', max_length=14),
        ),
    ]
