# Generated by Django 3.0.8 on 2020-08-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_token_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('password', models.CharField(blank=True, max_length=400, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='seller',
            name='display_picture',
            field=models.ImageField(blank=True, default=True, upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='seller',
            name='user_type',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='wallpaper',
            field=models.ImageField(blank=True, default=True, upload_to='images/products'),
        ),
    ]
