# Generated by Django 3.0.8 on 2020-08-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200803_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyersauthentication',
            name='email',
        ),
    ]
