# Generated by Django 3.0.8 on 2020-08-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200805_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='user_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='businessaddress',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='display_picture',
            field=models.ImageField(blank=True, upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='token',
            name='productcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='user_type',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='wallpaper',
            field=models.ImageField(blank=True, upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='display_picture',
            field=models.ImageField(blank=True, upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='wallpaper',
            field=models.ImageField(blank=True, upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='token',
            name='password',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
