# Generated by Django 3.0.8 on 2020-08-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('user_address', models.CharField(blank=True, max_length=250)),
                ('seller_id', models.CharField(blank=True, max_length=200)),
                ('quantity', models.IntegerField(blank=True, default=1, max_length=100)),
                ('seller_address', models.CharField(blank=True, max_length=400)),
                ('product_image', models.ImageField(blank=True, upload_to='images/products')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_packed', models.BooleanField(blank=True, default=False, null=True)),
                ('is_delivered', models.BooleanField(blank=True, default=False, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=100, null=True)),
                ('order_place_time', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
