# Generated by Django 3.0.8 on 2020-08-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20200806_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
