# Generated by Django 3.0.8 on 2020-08-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=3000)),
                ('product_rating', models.IntegerField()),
                ('product_price', models.BigIntegerField()),
                ('product_shop_name', models.CharField(max_length=500)),
                ('product_shop_address', models.CharField(max_length=600)),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
