# Generated by Django 3.0.8 on 2020-08-03 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_pub_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('product_name', models.CharField(default='', max_length=100)),
                ('product_value', models.CharField(default='', max_length=100)),
                ('product_description', models.CharField(default='', max_length=3000)),
                ('product_rating', models.IntegerField(default=0)),
                ('product_price', models.BigIntegerField(default=0)),
                ('product_shop_name', models.CharField(default='', max_length=500)),
                ('product_shop_address', models.CharField(default='', max_length=600)),
                ('discount', models.IntegerField(default=0)),
                ('category', models.CharField(default='', max_length=300)),
                ('product_image', models.ImageField(default='', upload_to='products/images')),
            ],
        ),
    ]
