# Generated by Django 3.0.8 on 2020-08-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_pub_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_description',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_shop_address',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_shop_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
