# Generated by Django 3.0.8 on 2020-08-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='product_value',
        ),
    ]
