# Generated by Django 3.0.8 on 2020-08-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200803_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='product_id',
            new_name='id',
        ),
    ]
