# Generated by Django 3.0.8 on 2020-08-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200803_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='product_pub_date',
        ),
    ]
