# Generated by Django 3.0.8 on 2020-08-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productmodel_product_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='seller_id',
            field=models.UUIDField(default='', editable=False),
        ),
    ]
