# Generated by Django 3.0.8 on 2020-08-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200803_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='seller_id',
        ),
    ]
