# Generated by Django 3.0.8 on 2020-08-03 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productmodel_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='seller_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
