# Generated by Django 3.0.8 on 2020-08-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productmodel_seller_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='seller_id',
        ),
    ]
